# Generated by Django 3.1.4 on 2021-12-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='requirement',
            field=models.TextField(null=True),
        ),
    ]
