# Generated by Django 3.2.9 on 2022-01-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220106_1959'),
        ('pages', '0006_post_email'),
    ]

    operations = [
    ]
