# Generated by Django 3.2.9 on 2022-01-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
    ]
