# Generated by Django 3.2.9 on 2022-01-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_deptlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptlist',
            old_name='department_name',
            new_name='name',
        ),
    ]
