# Generated by Django 3.2.9 on 2022-01-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_department_name_deptlist_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeptList',
        ),
        migrations.AlterField(
            model_name='post',
            name='dept_name',
            field=models.CharField(choices=[('Africana Studies', 'Africana Studies'), ('Anthropology', 'Anthropology'), ('Archaeological Studies', 'Archaeological Studies'), ('Art History', 'Art History'), ('Studio Art', 'Studio Art'), ('Athletics and Physical Education', 'Athletics And Physical Education'), ('Biology', 'Biology'), ('Chemistry and Biochemistry', 'Chemistry And Biochemistry'), ('Cinema Studies', 'Cinema Studies'), ('Classics', 'Classics'), ('Comparative American Studies', 'Comparative American Studies'), ('Comparative Literature', 'Comparative Literature'), ('Computer Science', 'Computer Science'), ('Creative Writing', 'Creative Writing'), ('Dance', 'Dance'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('East Asian Studies', 'East Asian Studies'), ('Economics', 'Economics'), ('Engineering', 'Engineering'), ('English', 'English'), ('Environmental Studies', 'Environmental Studies'), ('French', 'French'), ('Italian', 'Italian'), ('Gender, Sexuality, and Feminist Studies', 'Gender Sexuality And Feminist Studies'), ('Geology', 'Geology'), ('German Language and Literatures', 'German Language And Literatures'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Jewish Studies', 'Jewish Studies'), ('Latin American Studies', 'Latin American Studies'), ('Law and Society', 'Law And Society'), ('Learning Across the Disciplines', 'Learning Across Disciplines'), ('Mathematics', 'Mathematics'), ('Middle East and North Africa Studies', 'Middle East And North Africa Studies'), ('Musical Studies', 'Musical Studies'), ('Neuroscience', 'Neuroscience'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Astronomy', 'Astronomy'), ('Politics', 'Politics'), ('Psychology', 'Psychology'), ('Religion', 'Religion'), ('Rhetoric and Composition', 'Rhetoric And Composition'), ('Russian Language, Literature and Culture', 'Russian Language Literature And Culture'), ('Russian and East European Studies', 'Russian And East European Studies'), ('Sociology', 'Sociology'), ('Theater', 'Theater'), ('Other than academic', 'Non Academic')], default='Other than academic', max_length=120),
        ),
    ]
