# Generated by Django 3.1.4 on 2022-01-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20220122_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='Date_Posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deadline',
            new_name='Deadline',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dept_name',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='Descrption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='requirement',
            new_name='Requirement',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='yourname',
            new_name='Your_Name',
        ),
    ]
