# Generated by Django 3.1.4 on 2022-01-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20220123_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Descrption',
            new_name='Description',
        ),
    ]
